backend:
  name: github
  repo: arzijem/website
  branch: main
  base_url: https://sveltia-auth.arrzije-m.workers.dev

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    format: "json"

    fields:
      - { label: "Title (English)", name: "title_en", widget: "string" }
      - { label: "Title (Italian)", name: "title_it", widget: "string" }
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Grid Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Full Project Story (English)", name: "body_en", widget: "markdown", required: false }
      - { label: "Full Project Story (Italian)", name: "body_it", widget: "markdown", required: false }
      - { label: "Gallery Pictures", name: "gallery", widget: "list", field: { label: "Photo", name: "image", widget: "image" }, required: false }
